name: Workflow Example

on:
  push:
    branches:
    - master

jobs:
  exec-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
          lfs: true    
      - run: echo Hello actions
      - run: ./exec.bat
      - run: echo $env:GITHUB_WORKSPACE
