name: Workflow Example

on:
  push:
    branches:
    - master

jobs:
  exec-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1     
      - run: echo Hello actions
      - run: ./exec.bat
